//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Comet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Comet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Comet {
            get {
                object obj = ResourceManager.GetObject("Comet", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Comet
        ///{
        ///    #region Namespace
        ///
        ///    using System;
        ///
        ///    #endregion
        ///
        ///    internal class ConsoleManager
        ///    {
        ///        #region Events
        ///
        ///        /// &lt;summary&gt;Draws a line across the console.&lt;/summary&gt;
        ///        /// &lt;param name=&quot;symbol&quot;&gt;The symbol to draw.&lt;/param&gt;
        ///        public static void DrawLine(string symbol = &quot;-&quot;)
        ///        {
        ///            for (var i = 0; i &lt; Console.WindowWidth; i++)
        ///            {
        ///                Console.Write(symbol);
        ///            }
        ///        }
        ///
        ///        #endregion
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ConsoleManager {
            get {
                return ResourceManager.GetString("ConsoleManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Comet
        ///{
        ///    internal class Installer
        ///    {
        ///        public static void InstallData()
        ///        {
        ///            
        ///        }
        ///    }
        ///}.
        /// </summary>
        internal static string Installer {
            get {
                return ResourceManager.GetString("Installer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Comet
        ///{
        ///    #region Namespace
        ///
        ///    using System;
        ///    using System.Diagnostics;
        ///    using System.Globalization;
        ///    using System.IO;
        ///    using System.Reflection;
        ///    using System.Resources;
        ///    using System.Text;
        ///    using System.Windows.Forms;
        ///
        ///    #endregion
        ///
        ///    // TODO: Install app.
        ///    // TODO: Restart app.
        ///    public class CometInstaller
        ///    {
        ///        #region Properties
        ///
        ///        private static bool Installed { get; set; }
        ///
        ///        private static string InstallFiles { ge [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MainEntryPoint {
            get {
                return ResourceManager.GetString("MainEntryPoint", resourceCulture);
            }
        }
    }
}
