//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PackageManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PackageManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Comet
        ///{
        ///    #region Namespace
        ///
        ///    using System;
        ///    using System.Net;
        ///
        ///    #endregion
        ///
        ///    public class Installer
        ///    {
        ///        #region Events
        ///
        ///        public static void DownloadData()
        ///        {
        ///            // Verify internet connection
        ///
        ///            // Todo: Download file or multiple packages?
        ///        }
        ///
        ///        /// &lt;summary&gt;Get the url status code.&lt;/summary&gt;
        ///        /// &lt;param name=&quot;url&quot;&gt;The url.&lt;/param&gt;
        ///        /// &lt;param name=&quot;timeout&quot;&gt;The timeout.&lt;/param&gt;
        ///        /// &lt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Installer {
            get {
                return ResourceManager.GetString("Installer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Comet
        ///{
        ///    #region Namespace
        ///
        ///    using System;
        ///    using System.Collections.Generic;
        ///    using System.Diagnostics;
        ///    using System.Globalization;
        ///    using System.IO;
        ///    using System.Reflection;
        ///    using System.Resources;
        ///    using System.Windows.Forms;
        ///
        ///    #endregion
        ///
        ///    // TODO: Download data
        ///    // TODO: extract data, and install.
        ///    // TODO: Restart app.
        ///    public class MainEntryPoint
        ///    {
        ///        #region Properties
        ///
        ///        private static string DownloadLink {  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MainEntryPoint {
            get {
                return ResourceManager.GetString("MainEntryPoint", resourceCulture);
            }
        }
    }
}
